/**
 * Structured error codes for i18n-friendly error handling.
 * Backend returns { code, message }, frontend maps code → localized text.
 */
export const ErrorCodes = {
  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_REFRESH_INVALID: 'AUTH_REFRESH_INVALID',
  AUTH_ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
  AUTH_BRUTE_FORCE_LOCKED: 'AUTH_BRUTE_FORCE_LOCKED',

  // Billing
  BILLING_PAYMENT_DUE: 'BILLING_PAYMENT_DUE',
  BILLING_INSUFFICIENT_BALANCE: 'BILLING_INSUFFICIENT_BALANCE',

  // Products
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_ALREADY_TRACKED: 'PRODUCT_ALREADY_TRACKED',

  // Discovery
  DISCOVERY_INVALID_INPUT: 'DISCOVERY_INVALID_INPUT',
  DISCOVERY_CATEGORY_NOT_FOUND: 'DISCOVERY_CATEGORY_NOT_FOUND',
  DISCOVERY_RUN_ACTIVE: 'DISCOVERY_RUN_ACTIVE',

  // AI
  AI_QUOTA_EXCEEDED: 'AI_QUOTA_EXCEEDED',

  // General
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
